# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.   
     db:
      # We use the predefined Postgres image.
      image: postgres:9.6
      environment:
         # Set user/password for Postgres.
         POSTGRES_USER: 'postgres'
         POSTGRES_PASSWORD: 'Pass1234!'
         # Set a path where Postgres should store the data.
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      # ports:
      #    - '5432:5432'
      volumes:
         - pgdata:/var/lib/postgresql/data
     phoenix-service:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: ./todo_service/
      
      environment:
         # Variables to connect to our Postgres server.
         PGUSER: 'postgres' 
         PGPASSWORD: 'Pass1234!'
         PGDATABASE: 'todo_api_dev'
         PGPORT: 5432
         # Hostname of our Postgres container.
         PGHOST: db
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - 4001:4001
      depends_on:
      - db
     phoenix-client:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: ./todo_client/
      depends_on: 
         - phoenix-service
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - 4000:4000
 
# Define the volumes.
volumes:
   pgdata:


# networks:
#     default:
#         external:
#             name: todo_network


